import { Box,Check,RotateCcw,Search,X } from "lucide-react";
import { useMemo,useState } from "react";
const TYPES=[["temperature_sensor","Sensor temperature"],["temperature_humidity_sensor","Sensor temperature/lagështi"],["occupancy_sensor","Sensor pranie"],["smoke_detector","Detektor tymi"],["energy_meter","Matës energjie"],["door_sensor","Sensor dere"],["security_camera","Kamerë sigurie"],["emergency_button","Buton emergjence"],["equipment_status_sensor","Sensor pajisjeje"],["computer","Kompjuter"],["server_rack","Server rack"],["other","Objekt tjetër"]];
const SURFACES=[["wall","Mur"],["ceiling","Tavan"],["floor","Dysheme"]];
export function AssetPlacementPanel({placement,library=[]}) {
  const [tab,setTab]=useState("existing"),[search,setSearch]=useState("");
  const matches=useMemo(()=>library.filter((item)=>item.has3dModel&&`${item.name} ${item.displayName} ${item.code} ${item.type}`.toLowerCase().includes(search.toLowerCase())),[library,search]);
  if(!placement.open)return null;const field=(key)=>(event)=>placement.update({[key]:event.target.value,...(key==="assetType"?{name:event.target.options[event.target.selectedIndex].text}:{})});
  return <aside className="twin-placement-panel twin-equipment-drawer" aria-label="Shto pajisje në Digital Twin"><header><div><span>Digital Twin Editor</span><h2>Shto pajisje në Digital Twin</h2></div><button type="button" onClick={placement.cancel} aria-label="Mbyll"><X size={17}/></button></header><nav><button type="button" className={tab==="existing"?"active":""} onClick={()=>setTab("existing")}>Pajisje ekzistuese</button><button type="button" className={tab==="new"?"active":""} onClick={()=>setTab("new")}>Objekt i ri</button></nav>
    {tab==="existing"?<div className="twin-equipment-library"><label className="twin-equipment-search"><Search size={14}/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Kërko pajisje..."/></label>{matches.length?matches.map((item)=><article key={item.visualAssetId}><Box size={18}/><div><strong>{item.displayName||item.name}</strong><span>{item.code} · {item.type}</span><small>{item.zoneName||"Pa zonë"} · {item.status}</small></div><button type="button" onClick={()=>{placement.update({name:item.name,assetType:"other",parentEquipmentId:item.equipmentId,visualAssetId:item.visualAssetId,zoneId:String(item.zoneId??placement.draft.zoneId),mountingSurface:"floor",position:null});setTab("new");}}>Vendos</button></article>):<p>Nuk ka pajisje me model 3D për këtë laborator.</p>}</div>:<div className="twin-placement-fields"><label>Lloji i pajisjes<select value={placement.draft.assetType} onChange={field("assetType")}>{TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Emri<input value={placement.draft.name} onChange={field("name")}/></label><label>Asset ID<input value={placement.draft.assetCode} onChange={field("assetCode")}/></label><label>Zona<select value={placement.draft.zoneId} onChange={field("zoneId")}>{placement.zones.map((zone)=><option key={zone.id} value={zone.sourceId}>{zone.name}</option>)}</select></label><label>Sipërfaqja<select value={placement.draft.mountingSurface} onChange={field("mountingSurface")}>{SURFACES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="twin-rotate-placement" type="button" onClick={()=>placement.update({rotation:{...placement.draft.rotation,y:placement.draft.rotation.y+Math.PI/4}})}><RotateCcw size={15}/> Rrotullo 45°</button><p className={placement.validation.valid?"valid":"invalid"}>{placement.validation.reason}</p>{placement.error&&<p className="invalid">{placement.error}</p>}</div>}
    <footer><button type="button" onClick={placement.cancel}>Anulo</button><button type="button" disabled={!placement.validation.valid||placement.saving} onClick={placement.confirm}><Check size={15}/>{placement.saving?"Duke ruajtur...":"Konfirmo"}</button></footer></aside>;
}
