/* eslint-disable react/no-unknown-property */
import { Clone,useGLTF } from "@react-three/drei";
import { memo,useMemo } from "react";
import { rackSlots, workstationSlots, zoneKind } from "./zone-layout.js";
import { modelTransform } from "./model-transforms.js";

const ROOT="/models/digital-twin";
const MODELS={desk:`${ROOT}/SchoolDesk_01/SchoolDesk_01_1k.gltf`,chair:`${ROOT}/SchoolChair_01/SchoolChair_01_1k.gltf`,office:`${ROOT}/metal_office_desk/metal_office_desk_1k.gltf`,laptop:`${ROOT}/classic_laptop/classic_laptop_1k.gltf`,shelf:`${ROOT}/steel_frame_shelves_01/steel_frame_shelves_01_1k.gltf`,rack:`${ROOT}/server-rack.glb`,drill:`${ROOT}/drill_press_01/drill_press_01_1k.gltf`,extinguisher:`${ROOT}/korean_fire_extinguisher_01/korean_fire_extinguisher_01_1k.gltf`};
function Model({src,height,rotation=0}) { const gltf=useGLTF(src);const fit=useMemo(()=>modelTransform(gltf.scene,height),[gltf.scene,height]);return <group scale={fit.scale} rotation={[0,rotation,0]}><group position={fit.offset}><Clone object={gltf.scene} castShadow receiveShadow/></group></group>; }
function At({zone,x,z,rotation=0,children}) { return <group position={[zone.center[0]+x*zone.size[0],.025,zone.center[1]+z*zone.size[1]]} rotation={[0,rotation,0]}>{children}</group>; }
function DeskSet({office=false}) { return <group><Model src={office?MODELS.office:MODELS.desk} height={office?.76:.72}/><group position={[0,office?.77:.72,-.05]}><Model src={MODELS.laptop} height={.18}/></group><group position={[0,0,.58]} rotation={[0,Math.PI,0]}><Model src={MODELS.chair} height={.82}/></group></group>; }
function assetCount(assets,type){return assets.filter((asset)=>asset.type===type).length;}
function Classroom({zone,assets}) { return <group>{workstationSlots(zone).slice(assetCount(assets,"workstation")).map((slot,index)=><At key={index} zone={zone} x={slot.x} z={slot.z}><DeskSet/></At>)}<At zone={zone} x={0} z={-.4}><DeskSet office/></At></group>; }
function ControlLab({zone,assets}) { return <group>{workstationSlots(zone).slice(assetCount(assets,"workstation")).map((slot,index)=><At key={index} zone={zone} x={slot.x} z={slot.z}><DeskSet office/></At>)}{!assetCount(assets,"network-rack")&&rackSlots(zone,"network-rack").map((slot,index)=><At key={index} zone={zone} x={slot.x} z={slot.z}><Model src={MODELS.rack} height={1.85}/></At>)}</group>; }
function EngineeringLab({zone,assets}) { return <group>{workstationSlots(zone).slice(assetCount(assets,"workstation")).map((slot,index)=><At key={index} zone={zone} x={slot.x} z={slot.z}><DeskSet office/></At>)}<At zone={zone} x={-.38} z={.25}><Model src={MODELS.drill} height={1.4}/></At><At zone={zone} x={.36} z={.28}><Model src={MODELS.shelf} height={1.65} rotation={Math.PI/2}/></At></group>; }
function Documents(){const colors=["#EEE8D8","#C7B889","#7C8B70","#78658F","#B8B5AA"];return <group>{[.48,.88,1.28].flatMap((height,row)=>Array.from({length:5},(_,index)=><mesh key={`${row}-${index}`} castShadow position={[-.24+index*.12,height,0]} rotation={[0,0,(index%3-1)*.025]}><boxGeometry args={[.085,.25+(index%2)*.04,.22]}/><meshStandardMaterial color={colors[(row+index)%colors.length]} roughness={.82}/></mesh>))}</group>;}
function Storage({zone,assets}) { return <group>{rackSlots(zone,"storage-rack").slice(assetCount(assets,"storage-rack")).map((slot,index)=><At key={index} zone={zone} x={slot.x} z={slot.z}><Model src={MODELS.shelf} height={1.7}/><Documents/></At>)}</group>; }
function Safety({zone}) { return <group><At zone={zone} x={-.38} z={-.35}><Model src={MODELS.extinguisher} height={.78}/></At><At zone={zone} x={.22} z={-.25}><Model src={MODELS.shelf} height={1.45} rotation={Math.PI/2}/></At></group>; }
function FurnishZone({zone,assets}) { const kind=zoneKind(zone);if(kind==="robotics")return null;if(kind==="classroom")return <Classroom zone={zone} assets={assets}/>;if(kind==="storage")return <Storage zone={zone} assets={assets}/>;if(kind==="safety")return <Safety zone={zone}/>;if(kind==="engineering")return <EngineeringLab zone={zone} assets={assets}/>;return <ControlLab zone={zone} assets={assets}/>; }
export const ClassroomFurnishings=memo(function ClassroomFurnishings({zones=[],assets=[],visible=true}) { if(!visible)return null;return <group>{zones.map((zone)=><FurnishZone key={zone.id} zone={zone} assets={assets.filter((asset)=>asset.zoneId===zone.id)}/>)}</group>; });
