import { useMemo,useState } from "react";
import { Box,ChevronDown,Copy,FolderTree,Image,Move3d,Plus,Rotate3d,Scale3d,Trash2,Undo2 } from "lucide-react";

export function SceneEditorPanel({zones=[],operations,selection,onSelect,onAdd,canManage,transformMode,onTransformMode,onReset,onDuplicate,onDelete}) {
  const [tab,setTab]=useState("hierarchy"),[collapsed,setCollapsed]=useState(false);
  const grouped=useMemo(()=>zones.map((zone)=>({...zone,items:operations.placements.filter((item)=>String(item.zoneId)===String(zone.sourceId)||item.zoneName===zone.name)})),[operations.placements,zones]);
  const selected=selection?.kind==="placement"?selection.item:null;
  return <aside className={`twin-scene-editor ${collapsed?"collapsed":""}`}>
    <header><div><FolderTree size={16}/><strong>Objektet e laboratorit</strong></div><button type="button" aria-label={collapsed?"Hap panelin":"Mbyll panelin"} onClick={()=>setCollapsed((value)=>!value)}><ChevronDown size={16}/></button></header>
    {!collapsed&&<><nav><button type="button" className={tab==="hierarchy"?"active":""} onClick={()=>setTab("hierarchy")}>Hierarkia</button><button type="button" className={tab==="library"?"active":""} onClick={()=>setTab("library")}>Asset Library</button></nav>
      <div className="twin-scene-editor-content">{tab==="hierarchy"?<div className="twin-hierarchy"><section><h3>Struktura</h3><span>Dysheme · Mure · Tavan · Dyer</span></section>{grouped.map((zone)=><section key={zone.id}><h3>{zone.name}<b>{zone.items.length}</b></h3>{zone.items.length?zone.items.map((item)=><button type="button" className={selected?.id===item.id?"active":""} key={item.id} onClick={()=>onSelect({kind:"placement",item})}><Box size={14}/><span>{item.name}</span><i className={`state-${item.status}`}/></button>):<span>Pa objekte të vendosura</span>}</section>)}</div>:<div className="twin-asset-library">{operations.library.length?operations.library.map((item)=><article key={item.visualAssetId}><div>{item.assetKind==="image"?<Image size={19}/>:<Box size={19}/>}</div><section><strong>{item.displayName||item.name}</strong><span>{item.type} · {item.placedCount} në skenë</span>{item.assetKind==="image"&&<small>Pa model 3D</small>}</section>{canManage&&item.has3dModel&&<button type="button" aria-label={`Shto ${item.name} në skenë`} onClick={()=>onAdd({name:item.name,assetType:"other",parentEquipmentId:item.equipmentId,visualAssetId:item.visualAssetId,zoneId:item.zoneId,mountingSurface:"floor"})}><Plus size={16}/></button>}</article>):<div className="twin-library-empty"><Box size={22}/><strong>Nuk ka asete 3D</strong><span>Shtoni model nga detajet e pajisjes.</span></div>}</div>}</div>
      {selected&&canManage&&<footer><div className="twin-transform-tools"><button type="button" className={transformMode==="translate"?"active":""} onClick={()=>onTransformMode("translate")} title="Lëviz"><Move3d size={15}/></button><button type="button" className={transformMode==="rotate"?"active":""} onClick={()=>onTransformMode("rotate")} title="Rrotullo"><Rotate3d size={15}/></button><button type="button" className={transformMode==="scale"?"active":""} onClick={()=>onTransformMode("scale")} title="Ndrysho madhësinë"><Scale3d size={15}/></button><button type="button" onClick={onReset} title="Rikthe transformin"><Undo2 size={15}/></button><button type="button" onClick={onDuplicate} title="Dyfisho"><Copy size={15}/></button><button type="button" className="danger" onClick={onDelete} title="Hiq nga skena"><Trash2 size={15}/></button></div><span>Ndryshimet ruhen kur përfundon transformimi.</span></footer>}</>}
  </aside>;
}
