import { ChevronRight,Copy,Move3d,Rotate3d,Scale3d,Trash2,X } from "lucide-react";
import { useEffect,useState } from "react";

function MiniChart({history=[]}) { const values=history.map((point)=>Number(point.value));const min=Math.min(...values,0),max=Math.max(...values,1),range=Math.max(1,max-min);const points=values.map((value,index)=>`${(index/Math.max(1,values.length-1))*100},${38-((value-min)/range)*32}`).join(" ");return <svg className="twin-mini-chart" viewBox="0 0 100 42" preserveAspectRatio="none" aria-label="Historia e vlerave"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>; }
function PlacementInspector({item,transformMode,onTransformMode,onUpdate,onDuplicate,onDelete}) { const [draft,setDraft]=useState({position:item.position,rotation:item.rotation,scale:item.scale});useEffect(()=>setDraft({position:item.position,rotation:item.rotation,scale:item.scale}),[item]);const field=(group,key)=>(event)=>setDraft((current)=>({...current,[group]:{...current[group],[key]:Number(event.target.value)}}));const save=()=>onUpdate?.(item,draft);return <section className="twin-placement-inspector"><div className="twin-inspector-tools"><button type="button" className={transformMode==="translate"?"active":""} onClick={()=>onTransformMode("translate")}><Move3d size={14}/> Lëviz</button><button type="button" className={transformMode==="rotate"?"active":""} onClick={()=>onTransformMode("rotate")}><Rotate3d size={14}/> Rrotullo</button><button type="button" className={transformMode==="scale"?"active":""} onClick={()=>onTransformMode("scale")}><Scale3d size={14}/> Madhësia</button></div>{[["position","Pozicioni"],["rotation","Rotacioni"],["scale","Përmasa"]].map(([group,label])=><label key={group}><span>{label}</span><div>{["x","y","z"].map((axis)=><input key={axis} type="number" step={group==="rotation"?.1:.05} value={Number(draft[group]?.[axis]??0)} onChange={field(group,axis)} onBlur={save} aria-label={`${label} ${axis.toUpperCase()}`}/>)}</div></label>)}<div className="twin-inspector-actions"><button type="button" onClick={onDuplicate}><Copy size={14}/> Dyfisho</button><button type="button" className="danger" onClick={onDelete}><Trash2 size={14}/> Largo objektin</button></div></section>; }
export function TwinSelectionPanel({selection,history,onClose,onFocus,canEdit=false,transformMode,onTransformMode,onUpdate,onDuplicate,onDelete}) {
  if(!selection)return null;
  const item=selection.item,isSensor=selection.kind==="sensor",isPlacement=selection.kind==="placement",isZone=selection.kind==="zone";
  return <aside className="twin-selection-panel" aria-label="Detajet e objektit të zgjedhur"><div className="twin-panel-head"><div><span>{isZone?"Zonë laboratorike":isSensor?"Sensor IoT":"Asset fizik"}</span><h2>{item.name}</h2></div><button type="button" onClick={onClose} aria-label="Mbyll panelin"><X size={18}/></button></div>
    <div className={`twin-object-state state-${item.state??item.status}`}><i/><strong>{item.state??item.status}</strong><span>Përditësuar {new Intl.DateTimeFormat("sq-AL",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(item.lastUpdate))}</span></div>
    <dl className="twin-object-details"><div><dt>ID</dt><dd>{item.code??item.assetCode??item.id}</dd></div><div><dt>Zona</dt><dd>{isZone?item.name:(item.zoneName??item.zoneId??"Pa zonë")}</dd></div><div><dt>Tipi</dt><dd>{item.type}</dd></div>
      {isZone?<><div><dt>Pajisje</dt><dd>{item.deviceCount??0}</dd></div><div><dt>Sensorë</dt><dd>{item.sensorCount??0}</dd></div><div><dt>Alarme aktive</dt><dd>{item.alertCount??0}</dd></div></>:isSensor?<><div><dt>Matja</dt><dd>{item.value} {item.unit}</dd></div><div><dt>Statusi</dt><dd>{item.state}</dd></div><div><dt>Asset-i</dt><dd>{item.assetId??"Ambient"}</dd></div></>:isPlacement?<><div><dt>Pajisja</dt><dd>{item.parentEquipmentId??"Pa lidhje"}</dd></div><div><dt>Modeli</dt><dd>{item.visualAssetName??item.builtInKey??"Standard"}</dd></div><div><dt>Shkalla</dt><dd>{Number(item.scale?.x??1).toFixed(2)}×</dd></div></>:<><div><dt>Temperatura</dt><dd>{Number(item.temperature??0).toFixed(1)} °C</dd></div><div><dt>Energjia</dt><dd>{Number(item.energyWatts??0).toFixed(0)} W</dd></div><div><dt>Mirëmbajtja</dt><dd>{item.maintenance}</dd></div></>}
    </dl>{isPlacement&&canEdit&&<PlacementInspector item={item} transformMode={transformMode} onTransformMode={onTransformMode} onUpdate={onUpdate} onDuplicate={onDuplicate} onDelete={onDelete}/>} {!isZone&&<section className="twin-history-card"><div><strong>Historia live</strong><span>18 matjet e fundit</span></div><MiniChart history={history}/></section>}<button type="button" className="twin-focus-action" onClick={onFocus}>Fokuso në objekt <ChevronRight size={16}/></button></aside>;
}
