import { useCallback, useEffect, useState } from "react";
import { api } from "@/api/client.js";

export function useTwinOperations({laboratoryId,alerts,setAlerts}){
  const [events,setEvents]=useState([]);const [messages,setMessages]=useState([]);const [placements,setPlacements]=useState([]);const [library,setLibrary]=useState([]);const [channel,setChannel]=useState("laboratory");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!laboratoryId)return;setLoading(true);setError("");try{const [assetResponse,libraryResponse,eventResponse,messageResponse]=await Promise.all([api.get(`/api/digital-twin/${laboratoryId}/assets`),api.get(`/api/digital-twin/${laboratoryId}/asset-library`),api.get(`/api/digital-twin/${laboratoryId}/events?limit=100`),api.get(`/api/digital-twin/${laboratoryId}/messages?channel=${channel}`)]);setPlacements(assetResponse.data.assets??[]);setLibrary(libraryResponse.data.assets??[]);setEvents(eventResponse.data.events??[]);setMessages(messageResponse.data.messages??[]);}catch(requestError){setError(requestError.message);}finally{setLoading(false);}},[channel,laboratoryId]);
  useEffect(()=>{load();},[load]);
  const onRealtime=useCallback((eventName,payload)=>{if(eventName==="twin:asset-created")setPlacements(current=>[...current.filter(item=>item.id!==payload.id),payload]);if(eventName==="twin:asset-updated")setPlacements(current=>current.map(item=>item.id===payload.id?payload:item));if(eventName==="twin:asset-deleted")setPlacements(current=>current.filter(item=>item.id!==payload.id));if(eventName==="twin:message-created"&&payload.channel===channel)setMessages(current=>current.some(item=>item.id===payload.id)?current:[...current,payload]);if(eventName.startsWith("twin:")||eventName.startsWith("alert:"))api.get(`/api/digital-twin/${laboratoryId}/events?limit=100`).then(response=>setEvents(response.data.events??[])).catch(()=>{});},[channel,laboratoryId]);
  async function sendMessage(messageText){const response=await api.post(`/api/digital-twin/${laboratoryId}/messages`,{channel,messageText});setMessages(current=>current.some(item=>item.id===response.data.message.id)?current:[...current,response.data.message]);}
  async function acknowledgeAlert(alert){const response=await api.patch(`/api/alerts/${alert.id}/status`,{status:"acknowledged",notes:"Alarmi u pranua nga paneli Digital Twin."});setAlerts(current=>current.map(item=>String(item.id)===String(alert.id)?{...item,...response.data.alert}:item));}
  const payload=item=>({zoneId:item.zoneId,name:item.name,mountingSurface:item.mountingSurface,parentEquipmentId:item.parentEquipmentId??null,visualAssetId:item.visualAssetId??null,position:item.position,rotation:item.rotation,scale:item.scale??{x:1,y:1,z:1},visible:item.visible??true,status:item.status});
  async function updatePlacement(item,changes){const response=await api.put(`/api/digital-twin/${laboratoryId}/assets/${item.id}`,payload({...item,...changes}));setPlacements(current=>current.map(candidate=>candidate.id===item.id?response.data.asset:candidate));return response.data.asset;}
  async function removePlacement(item){await api.delete(`/api/digital-twin/${laboratoryId}/assets/${item.id}`);setPlacements(current=>current.filter(candidate=>candidate.id!==item.id));}
  async function duplicatePlacement(item){const suffix=`-COPY-${Date.now().toString().slice(-4)}`,assetCode=`${item.assetCode.slice(0,80-suffix.length)}${suffix}`;const response=await api.post(`/api/digital-twin/${laboratoryId}/assets`,{...payload({...item,position:{...item.position,x:item.position.x+.75}}),assetCode,assetType:item.assetType,installationDate:new Date().toISOString().slice(0,10)});setPlacements(current=>[...current,response.data.asset]);return response.data.asset;}
  return{events,messages,placements,library,channel,setChannel,loading,error,onRealtime,sendMessage,acknowledgeAlert,updatePlacement,removePlacement,duplicatePlacement,reload:load,alerts};
}
