import { query, withTransaction } from "../../database/query.js";

const assetSelect = `SELECT asset.id, asset.asset_code AS assetCode, asset.name,
  asset.asset_type AS assetType, asset.laboratory_id AS laboratoryId,
  asset.zone_id AS zoneId, zone.name AS zoneName,
  asset.mounting_surface AS mountingSurface,
  asset.parent_equipment_id AS parentEquipmentId,
  asset.position_x AS positionX, asset.position_y AS positionY, asset.position_z AS positionZ,
  asset.rotation_x AS rotationX, asset.rotation_y AS rotationY, asset.rotation_z AS rotationZ,
  asset.status, asset.installation_date AS installationDate,
  asset.installed_by_user_id AS installedByUserId, installer.full_name AS installedByName,
  asset.created_at AS createdAt, asset.updated_at AS updatedAt
  FROM digital_twin_assets asset
  INNER JOIN laboratory_zones zone ON zone.id=asset.zone_id AND zone.university_id=asset.university_id
  INNER JOIN users installer ON installer.id=asset.installed_by_user_id AND installer.university_id=asset.university_id`;

export function createDigitalTwinRepository(pool) {
  const findAsset = async (executor,{universityId,laboratoryId,assetId}) => (await query(executor,`${assetSelect} WHERE asset.university_id=? AND asset.laboratory_id=? AND asset.id=? LIMIT 1`,[universityId,laboratoryId,assetId]))[0]??null;
  const recordEvent = async (executor,event) => query(executor,`INSERT INTO digital_twin_events (university_id,laboratory_id,zone_id,asset_id,actor_user_id,event_type,severity,description,metadata_json) VALUES (?,?,?,?,?,?,?,?,?)`,[event.universityId,event.laboratoryId,event.zoneId??null,event.assetId??null,event.userId??null,event.eventType,event.severity??"info",event.description,event.metadata?JSON.stringify(event.metadata):null]);
  return {
    async listAssets({universityId,laboratoryId}) { return query(pool,`${assetSelect} WHERE asset.university_id=? AND asset.laboratory_id=? ORDER BY zone.name,asset.name`,[universityId,laboratoryId]); },
    async createAsset({universityId,laboratoryId,userId,asset}) { return withTransaction(pool,async(connection)=>{const result=await query(connection,`INSERT INTO digital_twin_assets (university_id,laboratory_id,zone_id,asset_code,name,asset_type,mounting_surface,parent_equipment_id,position_x,position_y,position_z,rotation_x,rotation_y,rotation_z,status,installation_date,installed_by_user_id) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM laboratory_zones zone WHERE zone.id=? AND zone.laboratory_id=? AND zone.university_id=?`,[universityId,laboratoryId,asset.zoneId,asset.assetCode,asset.name,asset.assetType,asset.mountingSurface,asset.parentEquipmentId,asset.position.x,asset.position.y,asset.position.z,asset.rotation.x,asset.rotation.y,asset.rotation.z,asset.status,asset.installationDate,userId,asset.zoneId,laboratoryId,universityId]);if(!result.affectedRows)return null;await recordEvent(connection,{universityId,laboratoryId,zoneId:asset.zoneId,assetId:result.insertId,userId,eventType:"asset.added",severity:"success",description:`Pajisja ${asset.assetCode} u vendos në laborator.`});return findAsset(connection,{universityId,laboratoryId,assetId:result.insertId});}); },
    async updateAsset({universityId,laboratoryId,userId,assetId,asset}) { return withTransaction(pool,async(connection)=>{const current=await findAsset(connection,{universityId,laboratoryId,assetId});if(!current)return null;const result=await query(connection,`UPDATE digital_twin_assets asset INNER JOIN laboratory_zones zone ON zone.id=? AND zone.laboratory_id=asset.laboratory_id AND zone.university_id=asset.university_id SET asset.zone_id=?,asset.name=?,asset.mounting_surface=?,asset.parent_equipment_id=?,asset.position_x=?,asset.position_y=?,asset.position_z=?,asset.rotation_x=?,asset.rotation_y=?,asset.rotation_z=?,asset.status=? WHERE asset.id=? AND asset.laboratory_id=? AND asset.university_id=?`,[asset.zoneId,asset.zoneId,asset.name,asset.mountingSurface,asset.parentEquipmentId,asset.position.x,asset.position.y,asset.position.z,asset.rotation.x,asset.rotation.y,asset.rotation.z,asset.status,assetId,laboratoryId,universityId]);if(!result.affectedRows)return null;await recordEvent(connection,{universityId,laboratoryId,zoneId:asset.zoneId,assetId,userId,eventType:"asset.moved",description:`Pajisja ${current.assetCode} u përditësua.`,metadata:{previousPosition:[current.positionX,current.positionY,current.positionZ]}});return findAsset(connection,{universityId,laboratoryId,assetId});}); },
    async deleteAsset({universityId,laboratoryId,userId,assetId}) { return withTransaction(pool,async(connection)=>{const current=await findAsset(connection,{universityId,laboratoryId,assetId});if(!current)return null;await recordEvent(connection,{universityId,laboratoryId,zoneId:current.zoneId,userId,eventType:"asset.removed",severity:"warning",description:`Pajisja ${current.assetCode} u largua.`,metadata:{assetId:String(assetId)}});await query(connection,"DELETE FROM digital_twin_assets WHERE id=? AND laboratory_id=? AND university_id=?",[assetId,laboratoryId,universityId]);return current;}); },
    async listEvents({universityId,laboratoryId,limit=100}) { return query(pool,`SELECT event.id,event.event_type AS eventType,event.severity,event.description,event.zone_id AS zoneId,zone.name AS zoneName,event.asset_id AS assetId,event.actor_user_id AS actorUserId,actor.full_name AS actorName,event.metadata_json AS metadata,event.created_at AS createdAt FROM digital_twin_events event LEFT JOIN laboratory_zones zone ON zone.id=event.zone_id AND zone.university_id=event.university_id LEFT JOIN users actor ON actor.id=event.actor_user_id AND actor.university_id=event.university_id WHERE event.university_id=? AND event.laboratory_id=? ORDER BY event.created_at DESC,event.id DESC LIMIT ${Math.min(200,Math.max(1,Number(limit)||100))}`,[universityId,laboratoryId]); },
    async listMessages({universityId,laboratoryId,channel,search=""}) { const params=[universityId,laboratoryId,channel];let extra="";if(search){extra=" AND message.message_text LIKE ?";params.push(`%${search}%`);}return query(pool,`SELECT message.id,message.channel,message.sender_type AS senderType,message.sender_user_id AS senderUserId,sender.full_name AS senderName,message.reply_to_message_id AS replyToMessageId,message.message_text AS messageText,message.created_at AS createdAt FROM digital_twin_messages message LEFT JOIN users sender ON sender.id=message.sender_user_id AND sender.university_id=message.university_id WHERE message.university_id=? AND message.laboratory_id=? AND message.channel=?${extra} ORDER BY message.created_at ASC,message.id ASC LIMIT 200`,params); },
    async createMessage({universityId,laboratoryId,userId,message}) { const result=await query(pool,"INSERT INTO digital_twin_messages (university_id,laboratory_id,sender_user_id,reply_to_message_id,channel,sender_type,message_text) VALUES (?,?,?,?,?,'user',?)",[universityId,laboratoryId,userId,message.replyToMessageId,message.channel,message.messageText]);return (await query(pool,`SELECT message.id,message.channel,message.sender_type AS senderType,message.sender_user_id AS senderUserId,sender.full_name AS senderName,message.reply_to_message_id AS replyToMessageId,message.message_text AS messageText,message.created_at AS createdAt FROM digital_twin_messages message LEFT JOIN users sender ON sender.id=message.sender_user_id AND sender.university_id=message.university_id WHERE message.id=? AND message.university_id=?`,[result.insertId,universityId]))[0]; },
  };
}
