import { z } from "zod";
import { AppError } from "../../utils/app-error.js";

const vector=z.object({x:z.coerce.number().finite().min(-100).max(100),y:z.coerce.number().finite().min(0).max(20),z:z.coerce.number().finite().min(-100).max(100)});
const assetTypes=["temperature_sensor","temperature_humidity_sensor","occupancy_sensor","smoke_detector","energy_meter","door_sensor","security_camera","emergency_button","equipment_status_sensor","computer","server_rack","other"];
const surfaces=["wall","ceiling","floor","table","equipment"];
const assetSchema=z.object({assetCode:z.string().trim().min(2).max(80).regex(/^[A-Za-z0-9_-]+$/).transform(v=>v.toUpperCase()),name:z.string().trim().min(2).max(160),assetType:z.enum(assetTypes),zoneId:z.coerce.number().int().positive().transform(String),mountingSurface:z.enum(surfaces),parentEquipmentId:z.coerce.number().int().positive().transform(String).nullable().optional().default(null),position:vector,rotation:vector.extend({y:z.coerce.number().finite().min(-6.284).max(6.284)}),status:z.enum(["online","offline","warning","critical","maintenance"]).default("online"),installationDate:z.iso.date().default(()=>new Date().toISOString().slice(0,10))});
const updateSchema=assetSchema.omit({assetCode:true,assetType:true,installationDate:true});
const messageSchema=z.object({channel:z.enum(["laboratory","technical","administrators"]),messageText:z.string().trim().min(1).max(2000),replyToMessageId:z.coerce.number().int().positive().transform(String).nullable().optional().default(null)});
const fail=(message="Të dhënat nuk janë të vlefshme.")=>new AppError({status:422,code:"VALIDATION_ERROR",message});
const missing=()=>new AppError({status:404,code:"NOT_FOUND",message:"Burimi i Digital Twin nuk u gjet."});
const normalize=(item)=>({...item,id:String(item.id),laboratoryId:item.laboratoryId?String(item.laboratoryId):undefined,zoneId:item.zoneId?String(item.zoneId):null,assetId:item.assetId?String(item.assetId):undefined,position:item.positionX===undefined?undefined:{x:Number(item.positionX),y:Number(item.positionY),z:Number(item.positionZ)},rotation:item.rotationX===undefined?undefined:{x:Number(item.rotationX),y:Number(item.rotationY),z:Number(item.rotationZ)}});
const assertChannelAccess=(channel,context)=>{const roles=new Set(context.roles??[]);const allowed=channel==="administrators"?["university_admin","lab_manager"]:channel==="technical"?["university_admin","lab_manager","technician"]:null;if(allowed&&!allowed.some(role=>roles.has(role)))throw new AppError({status:403,code:"FORBIDDEN",message:"Nuk keni leje për këtë kanal."});};

export function createDigitalTwinService({repository,realtimePublisher}){return{
  async listAssets(laboratoryId,context){return (await repository.listAssets({...context,laboratoryId})).map(normalize);},
  async createAsset(laboratoryId,input,context){const parsed=assetSchema.safeParse(input);if(!parsed.success)throw fail();try{const asset=await repository.createAsset({...context,laboratoryId,asset:parsed.data});if(!asset)throw missing();const normalized=normalize(asset);realtimePublisher?.publishTwinEvent({universityId:context.universityId,laboratoryId,eventName:"twin:asset-created",payload:normalized});return normalized;}catch(error){if(error?.code==="ER_DUP_ENTRY")throw new AppError({status:409,code:"ASSET_CODE_EXISTS",message:"Ky Asset ID ekziston tashmë."});throw error;}},
  async updateAsset(laboratoryId,assetId,input,context){const parsed=updateSchema.safeParse(input);if(!parsed.success)throw fail();const asset=await repository.updateAsset({...context,laboratoryId,assetId,asset:parsed.data});if(!asset)throw missing();const normalized=normalize(asset);realtimePublisher?.publishTwinEvent({universityId:context.universityId,laboratoryId,eventName:"twin:asset-updated",payload:normalized});return normalized;},
  async deleteAsset(laboratoryId,assetId,context){const asset=await repository.deleteAsset({...context,laboratoryId,assetId});if(!asset)throw missing();realtimePublisher?.publishTwinEvent({universityId:context.universityId,laboratoryId,eventName:"twin:asset-deleted",payload:{id:String(assetId)}});return normalize(asset);},
  async listEvents(laboratoryId,input,context){return (await repository.listEvents({...context,laboratoryId,limit:input.limit})).map(normalize);},
  async listMessages(laboratoryId,input,context){const channel=z.enum(["laboratory","technical","administrators"]).safeParse(input.channel??"laboratory");if(!channel.success)throw fail();assertChannelAccess(channel.data,context);return (await repository.listMessages({...context,laboratoryId,channel:channel.data,search:String(input.search??"").trim().slice(0,100)})).map(normalize);},
  async createMessage(laboratoryId,input,context){const parsed=messageSchema.safeParse(input);if(!parsed.success)throw fail();assertChannelAccess(parsed.data.channel,context);const message=normalize(await repository.createMessage({...context,laboratoryId,message:parsed.data}));realtimePublisher?.publishTwinEvent({universityId:context.universityId,laboratoryId,eventName:"twin:message-created",payload:message});return message;}
};}
