import assert from "node:assert/strict";
import test from "node:test";
import { createEquipmentAssetService } from "./service.js";

const context={universityId:"7",userId:"9",roles:["university_admin"],ipAddress:"127.0.0.1"};
test("uploads a valid GLB as a tenant-scoped equipment asset",async()=>{let received;const service=createEquipmentAssetService({storage:{save:async()=>({storedName:"safe.glb",relativePath:"uploads/safe.glb",checksumSha256:"a".repeat(64)}),remove:async()=>{}},repository:{attachFile:async input=>{received=input;return{id:4,equipmentId:12,assetKind:"model_3d",fileId:8,isPrimary:1,displayName:"Karrigia"};}}});const buffer=Buffer.alloc(12);buffer.write("glTF",0,"ascii");buffer.writeUInt32LE(2,4);const asset=await service.upload("12",{originalname:"chair.glb",size:12,buffer},{displayName:"Karrigia"},context);assert.equal(received.universityId,"7");assert.equal(received.equipmentId,"12");assert.equal(received.file.mimeType,"model/gltf-binary");assert.equal(asset.downloadUrl,"/api/files/8");assert.equal(asset.has3dModel,true);});
test("rejects an executable renamed as a GLB",async()=>{const service=createEquipmentAssetService({storage:{},repository:{}});await assert.rejects(()=>service.upload("12",{originalname:"unsafe.glb",size:8,buffer:Buffer.from("MZbinary")},{},context),error=>error.code==="INVALID_VISUAL_ASSET"&&error.status===422);});
test("removes the stored file when database attachment fails",async()=>{let removed="";const service=createEquipmentAssetService({storage:{save:async()=>({storedName:"safe.png",relativePath:"uploads/safe.png",checksumSha256:"b".repeat(64)}),remove:async path=>{removed=path;}},repository:{attachFile:async()=>{throw new Error("db failed");}}});const buffer=Buffer.from([137,80,78,71,13,10,26,10]);await assert.rejects(()=>service.upload("12",{originalname:"photo.png",size:8,buffer},{},context));assert.equal(removed,"uploads/safe.png");});
test("allows only catalogued built-in assets",async()=>{const service=createEquipmentAssetService({storage:{},repository:{attachBuiltIn:async input=>({id:5,equipmentId:input.equipmentId,assetKind:"built_in",builtInKey:input.builtInKey,isPrimary:1,displayName:input.displayName})}});await assert.rejects(()=>service.attachBuiltIn("12",{builtInKey:"unknown",displayName:"Unknown"},context));const asset=await service.attachBuiltIn("12",{builtInKey:"chair",displayName:"Karrige"},context);assert.equal(asset.builtInKey,"chair");});
