import path from "node:path";
import { z } from "zod";
import { requiresLaboratoryAssignment } from "../../middleware/require-laboratory-access.js";
import { AppError } from "../../utils/app-error.js";

const invalid=message=>new AppError({status:422,code:"INVALID_VISUAL_ASSET",message});
const missing=()=>new AppError({status:404,code:"NOT_FOUND",message:"Pajisja ose aseti vizual nuk u gjet."});
const builtIns=new Set(["chair","desk","computer","monitor","projector","camera","sensor","router","server_rack","lamp"]);
function validate(file){if(!file)throw invalid("Zgjidhni një skedar GLB, GLTF, PNG, JPG ose WebP.");const extension=path.extname(file.originalname).toLowerCase(),buffer=file.buffer;if(extension===".glb"&&buffer.length>=12&&buffer.subarray(0,4).toString("ascii")==="glTF"&&buffer.readUInt32LE(4)===2)return{extension,mimeType:"model/gltf-binary",assetKind:"model_3d"};if(extension===".gltf"){try{const document=JSON.parse(buffer.toString("utf8"));if(String(document?.asset?.version??"").startsWith("2")&&!([...(document.buffers??[]),...(document.images??[])].some(resource=>resource.uri&&!resource.uri.startsWith("data:")&&!resource.bufferView)))return{extension,mimeType:"model/gltf+json",assetKind:"model_3d"};}catch{}throw invalid("GLTF duhet të jetë version 2 dhe i vetë-përmbajtshëm.");}if([".jpg",".jpeg"].includes(extension)&&buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff)return{extension,mimeType:"image/jpeg",assetKind:"image"};if(extension===".png"&&buffer.length>=8&&buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return{extension,mimeType:"image/png",assetKind:"image"};if(extension===".webp"&&buffer.length>=12&&buffer.subarray(0,4).toString("ascii")==="RIFF"&&buffer.subarray(8,12).toString("ascii")==="WEBP")return{extension,mimeType:"image/webp",assetKind:"image"};throw invalid("Formati ose përmbajtja e skedarit nuk është e vlefshme.");}
const contextArgs=(context)=>({universityId:context.universityId,userId:context.userId,restrictToAssignments:requiresLaboratoryAssignment(context),ipAddress:context.ipAddress});
const normalize=item=>{const publicItem={...item};delete publicItem.relativePath;return{...publicItem,id:String(item.id),equipmentId:String(item.equipmentId),fileId:item.fileId?String(item.fileId):null,isPrimary:Boolean(item.isPrimary),downloadUrl:item.fileId?`/api/files/${item.fileId}`:null,has3dModel:item.assetKind==="model_3d"||item.assetKind==="built_in"};};
export function createEquipmentAssetService({repository,storage}){return{
 async list(equipmentId,context){return(await repository.list({...contextArgs(context),equipmentId})).map(normalize);},
 async upload(equipmentId,file,input,context){const checked=validate(file);const displayName=String(input.displayName??file.originalname).trim().slice(0,160);if(displayName.length<2)throw invalid("Shkruani emrin e asetit.");const stored=await storage.save({universityId:context.universityId,equipmentId,file,extension:checked.extension});try{const item=await repository.attachFile({...contextArgs(context),equipmentId,asset:{assetKind:checked.assetKind,displayName},file:{originalName:file.originalname,sizeBytes:file.size,...stored,mimeType:checked.mimeType}});if(!item)throw missing();return normalize(item);}catch(error){await storage.remove(stored.relativePath);throw error;}},
 async attachBuiltIn(equipmentId,input,context){const parsed=z.object({builtInKey:z.string().trim(),displayName:z.string().trim().min(2).max(160)}).safeParse(input);if(!parsed.success||!builtIns.has(parsed.data.builtInKey))throw invalid("Aseti i integruar nuk është i vlefshëm.");const item=await repository.attachBuiltIn({...contextArgs(context),equipmentId,...parsed.data});if(!item)throw missing();return normalize(item);},
 async remove(equipmentId,assetId,context){const item=await repository.remove({...contextArgs(context),equipmentId,assetId});if(!item)throw missing();if(item.relativePath)await storage.remove(item.relativePath);return normalize(item);}
};}
