import { useCallback,useEffect,useRef,useState } from "react";
import { Box,Check,FileUp,Image as ImageIcon,Trash2,UploadCloud } from "lucide-react";
import { api } from "@/api/client.js";
import { AssetPreview } from "./AssetPreview.jsx";
import { Button } from "./ui/button.jsx";

const MAX=25*1024*1024,allowed=new Set(["glb","gltf","png","jpg","jpeg","webp"]);
const BUILT_INS=[["chair","Karrige"],["desk","Tavolinë"],["computer","Kompjuter"],["monitor","Monitor"],["projector","Projektor"],["camera","Kamerë"],["sensor","Sensor"],["router","Router"],["server_rack","Server rack"],["lamp","Llambë"]];
export function EquipmentVisualAssets({equipmentId,canManage}){const[assets,setAssets]=useState([]),[selected,setSelected]=useState(null),[file,setFile]=useState(null),[builtIn,setBuiltIn]=useState("chair"),[busy,setBusy]=useState(false),[message,setMessage]=useState({type:"",text:""}),[dragging,setDragging]=useState(false);const inputRef=useRef(null);
 const load=useCallback(async()=>{try{const response=await api.get(`/api/equipment/${equipmentId}/visual-assets`);const list=response.data.assets??[];setAssets(list);setSelected(current=>list.find(item=>item.id===current?.id)??list[0]??null);}catch(error){setMessage({type:"error",text:error.message});}},[equipmentId]);useEffect(()=>{load();},[load]);
 function choose(next){const extension=next?.name.split(".").pop()?.toLowerCase();if(!next||!allowed.has(extension)){setFile(null);setMessage({type:"error",text:"Formati duhet të jetë GLB, GLTF, PNG, JPG ose WebP."});return;}if(next.size>MAX){setFile(null);setMessage({type:"error",text:"Aseti nuk mund të jetë më i madh se 25 MB."});return;}setFile(next);setMessage({type:"",text:""});}
 async function upload(){if(!file)return;setBusy(true);try{const body=new FormData();body.append("asset",file);body.append("displayName",file.name.replace(/\.[^.]+$/,""));const response=await api.post(`/api/equipment/${equipmentId}/visual-assets/upload`,body);setMessage({type:"success",text:"Aseti vizual u ngarkua me sukses."});setFile(null);await load();setSelected(response.data.asset);}catch(error){setMessage({type:"error",text:error.message});}finally{setBusy(false);}}
 async function selectBuiltIn(){setBusy(true);try{const label=BUILT_INS.find(item=>item[0]===builtIn)?.[1]??builtIn;const response=await api.post(`/api/equipment/${equipmentId}/visual-assets/built-in`,{builtInKey:builtIn,displayName:label});setMessage({type:"success",text:"Aseti i integruar u lidh me pajisjen."});await load();setSelected(response.data.asset);}catch(error){setMessage({type:"error",text:error.message});}finally{setBusy(false);}}
 async function remove(asset){if(!window.confirm(`Ta hiqni asetin “${asset.displayName}”?`))return;setBusy(true);try{await api.delete(`/api/equipment/${equipmentId}/visual-assets/${asset.id}`);setMessage({type:"success",text:"Aseti u hoq."});await load();}catch(error){setMessage({type:"error",text:error.message});}finally{setBusy(false);}}
 return <section className="equipment-visual-assets"><header><div><span>Digital Twin</span><h2>Aseti vizual / Modeli Digital Twin</h2><p>Menaxhoni modelin 3D, fotografinë ose asetin e integruar të pajisjes.</p></div><Box size={22}/></header>{message.text&&<p className={`form-message ${message.type}`} role="status">{message.text}</p>}<div className="equipment-assets-layout"><div className="equipment-asset-stage"><AssetPreview asset={selected}/>{selected&&<div className="asset-stage-meta"><div><strong>{selected.displayName}</strong><span>{selected.assetKind==="model_3d"?"Model 3D":selected.assetKind==="image"?"Imazh · Pa model 3D":"Aset i integruar"}</span></div>{canManage&&<button type="button" aria-label={`Hiq ${selected.displayName}`} onClick={()=>remove(selected)} disabled={busy}><Trash2 size={16}/></button>}</div>}</div><div className="equipment-asset-library"><h3>Asetet e pajisjes</h3>{assets.length?<div className="equipment-asset-list">{assets.map(asset=><button type="button" key={asset.id} className={selected?.id===asset.id?"active":""} onClick={()=>setSelected(asset)}><span>{asset.assetKind==="image"?<ImageIcon size={17}/>:<Box size={17}/>}</span><div><strong>{asset.displayName}</strong><small>{asset.isPrimary?"Primar":"Alternativ"}</small></div>{selected?.id===asset.id&&<Check size={15}/>}</button>)}</div>:<div className="asset-empty"><Box size={20}/><p>Kjo pajisje ende nuk ka aset vizual.</p></div>}{canManage&&<><div className="asset-divider"><span>Ngarko skedar</span></div><div className={`asset-dropzone ${dragging?"dragging":""}`} onDragOver={event=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);choose(event.dataTransfer.files[0]);}}><UploadCloud size={24}/><strong>{file?file.name:"Zvarrit skedarin këtu"}</strong><span>GLB, GLTF, PNG, JPG ose WebP · maksimumi 25 MB</span><Button type="button" variant="outline" size="sm" onClick={()=>inputRef.current?.click()}><FileUp size={15}/> Zgjidh skedar</Button><input ref={inputRef} type="file" accept=".glb,.gltf,.png,.jpg,.jpeg,.webp" hidden onChange={event=>choose(event.target.files[0])}/>{file&&<Button type="button" size="sm" onClick={upload} disabled={busy}>{busy?"Po ngarkohet…":"Ngarko asetin"}</Button>}</div><div className="asset-divider"><span>ose aset i integruar</span></div><div className="built-in-picker"><select value={builtIn} onChange={event=>setBuiltIn(event.target.value)}>{BUILT_INS.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><Button type="button" variant="outline" onClick={selectBuiltIn} disabled={busy}>Përdor asetin</Button></div></>}</div></div></section>;
}
