CREATE TABLE digital_twin_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  university_id BIGINT UNSIGNED NOT NULL,
  laboratory_id BIGINT UNSIGNED NOT NULL,
  zone_id BIGINT UNSIGNED NOT NULL,
  asset_code VARCHAR(80) NOT NULL,
  name VARCHAR(160) NOT NULL,
  asset_type ENUM('temperature_sensor','temperature_humidity_sensor','occupancy_sensor','smoke_detector','energy_meter','door_sensor','security_camera','emergency_button','equipment_status_sensor','computer','server_rack','other') NOT NULL,
  mounting_surface ENUM('wall','ceiling','floor','table','equipment') NOT NULL,
  parent_equipment_id BIGINT UNSIGNED NULL,
  position_x DECIMAL(9,4) NOT NULL,
  position_y DECIMAL(9,4) NOT NULL,
  position_z DECIMAL(9,4) NOT NULL,
  rotation_x DECIMAL(9,5) NOT NULL DEFAULT 0,
  rotation_y DECIMAL(9,5) NOT NULL DEFAULT 0,
  rotation_z DECIMAL(9,5) NOT NULL DEFAULT 0,
  status ENUM('online','offline','warning','critical','maintenance') NOT NULL DEFAULT 'online',
  installation_date DATE NOT NULL,
  installed_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_twin_assets_tenant_code (university_id, asset_code),
  UNIQUE KEY uq_twin_assets_id_university (id, university_id),
  KEY idx_twin_assets_lab_zone (university_id, laboratory_id, zone_id),
  CONSTRAINT fk_twin_assets_laboratory FOREIGN KEY (laboratory_id, university_id) REFERENCES laboratories (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_assets_zone FOREIGN KEY (zone_id, university_id) REFERENCES laboratory_zones (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_assets_parent FOREIGN KEY (parent_equipment_id, university_id) REFERENCES equipment (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_assets_installer FOREIGN KEY (installed_by_user_id, university_id) REFERENCES users (id, university_id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE digital_twin_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  university_id BIGINT UNSIGNED NOT NULL,
  laboratory_id BIGINT UNSIGNED NOT NULL,
  zone_id BIGINT UNSIGNED NULL,
  asset_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(80) NOT NULL,
  severity ENUM('info','success','warning','critical') NOT NULL DEFAULT 'info',
  description VARCHAR(500) NOT NULL,
  metadata_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_twin_events_tenant_lab_time (university_id, laboratory_id, created_at),
  CONSTRAINT fk_twin_events_laboratory FOREIGN KEY (laboratory_id, university_id) REFERENCES laboratories (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_events_zone FOREIGN KEY (zone_id, university_id) REFERENCES laboratory_zones (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_events_asset FOREIGN KEY (asset_id, university_id) REFERENCES digital_twin_assets (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_events_actor FOREIGN KEY (actor_user_id, university_id) REFERENCES users (id, university_id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE digital_twin_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  university_id BIGINT UNSIGNED NOT NULL,
  laboratory_id BIGINT UNSIGNED NOT NULL,
  sender_user_id BIGINT UNSIGNED NULL,
  reply_to_message_id BIGINT UNSIGNED NULL,
  channel ENUM('laboratory','technical','administrators') NOT NULL,
  sender_type ENUM('user','system') NOT NULL DEFAULT 'user',
  message_text VARCHAR(2000) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_twin_messages_id_university (id, university_id),
  KEY idx_twin_messages_tenant_lab_channel (university_id, laboratory_id, channel, created_at),
  CONSTRAINT fk_twin_messages_laboratory FOREIGN KEY (laboratory_id, university_id) REFERENCES laboratories (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_messages_sender FOREIGN KEY (sender_user_id, university_id) REFERENCES users (id, university_id) ON DELETE RESTRICT,
  CONSTRAINT fk_twin_messages_reply FOREIGN KEY (reply_to_message_id, university_id) REFERENCES digital_twin_messages (id, university_id) ON DELETE RESTRICT
) ENGINE=InnoDB;
